### ISSUE TITLE
build fails (cygwin)

### ISSUE THREAD

**Issue by mintty** [abishekvashok/cmatrix#120] opened 2021-01-30 18:39 UTC
no makefile and no configure script, so I tried `cmake .`, then make:

[ 50%] Building C object CMakeFiles/cmatrix.dir/cmatrix.c.o
/home/towo/tmp/cmatrix/cmatrix.c: In function ‘resize_screen’:
/home/towo/tmp/cmatrix/cmatrix.c:277:10: error: lvalue required as left operand of assignment
  277 |     COLS = win.ws_col;
      |          ^
/home/towo/tmp/cmatrix/cmatrix.c:278:11: error: lvalue required as left operand of assignment
  278 |     LINES = win.ws_row;
      |           ^
/home/towo/tmp/cmatrix/cmatrix.c:282:15: error: lvalue required as left operand of assignment
  282 |         LINES = 10;
      |               ^
/home/towo/tmp/cmatrix/cmatrix.c:285:14: error: lvalue required as left operand of assignment
  285 |         COLS = 10;
      |              ^
/home/towo/tmp/cmatrix/cmatrix.c: In function ‘main’:
/home/towo/tmp/cmatrix/cmatrix.c:560:41: error: ‘TIOCSTI’ undeclared (first use in this function)
  560 |                     ioctl(STDIN_FILENO, TIOCSTI, (char*)(str + i));
      |                                         ^~~~~~~

**Comment by abishekvashok** [comment] 2021-07-18 14:27
> no makefile and no configure script, so I tried cmake ., then make:

Hey, please either make the configure script with autoconf or, use the release version which contains configure script.

**Comment by mintty** [comment] 2021-07-18 14:43
There is no configure script in either the release archive or the repositoy.
autoconf says:
configure.ac:5: error: possibly undefined macro: AM_CONFIG_HEADER
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:6: error: possibly undefined macro: AM_INIT_AUTOMAKE
configure.ac:135: error: possibly undefined macro: AM_CONDITIONAL

**Comment by rashil2000** [comment] 2021-09-06 08:20
This is a duplicate of #40

**Comment by abishekvashok** [comment] 2021-09-06 08:32
Closing in favor of #40

**Closed as completed by abishekvashok** 2021-09-06 08:32 UTC
Labels: Bug
