### ISSUE TITLE
Does it support compiling under macOS?

### ISSUE THREAD

**Issue by JiangYongKang** [abishekvashok/cmatrix#16] opened 2017-09-22 07:41 UTC
I run `. /configure` after some warnings,` glibc6` can not work in mac?
```log
configure: WARNING:

*** neither the consolechars nor the setfont program was not found.  You
*** will not be able to see the characters in the matrix font in the
*** console without this program (it may still work in xterms). If you are
*** using Linux, the package containing this program is usually called
*** kbd, kbd-utils, or console-utils

checking for /usr/lib/kbd/consolefonts... no
checking for /usr/share/consolefonts... no
configure: WARNING:

*** You do not appear to have a consolefonts directory in a standard location
*** (/usr/lib/kbd or /usr/share), even though you appear to have the
*** consolechars and/or setfont command.  The matrix font for the console
*** will not be installed.  This means you will not be able to use the
*** matrix console font (and the -l command line switch) unless the font
*** is located in your current directory when you run CMatrix.

checking for mkfontdir... no
checking for /usr/lib/X11/fonts/misc... no
checking for /usr/X11R6/lib/X11/fonts/misc... no
configure: WARNING:

*** You do not appear to have an X window fonts directory in the standard
*** locations (/usr/lib/X11/fonts/misc or /usr/X11R6/lib/X11/fonts/misc). The
*** mtx.pcf font will not be installed.  This means you will probably not
*** be able to use the mtx fonts in your x terminals, and hence be unable
*** to use the -x command line switch.  Sorry about that...

checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating cmatrix.spec
config.status: creating config.h
config.status: config.h is unchanged
config.status: executing depfiles commands
```

**Comment by abishekvashok** [comment] 2017-09-22 11:16
Cmatrix requires the ncurses library and glibc6.
All the warning have been generated because you are not on linux.

We are thinking of porting it to mac and windows and would get back into this later this month. Mostly for me, this month is a very busy one.

**Comment by nlutsenko** [comment] 2017-10-13 18:33
FWIW homebrew on macOS actually has cmatrix, which looks like is getting compiled on macOS no problem.
The source of the brew formula is [here](https://github.com/Homebrew/homebrew-core/blob/master/Formula/cmatrix.rb).

And I was able to compile it from scratch (`brew install cmatrix -s`) (`-s` to compile instead of downloading a binary from cache).

**Comment by abishekvashok** [comment] 2017-10-18 12:22
brew has an old version of cmatrix I guess.

**Comment by abishekvashok** [comment] 2017-10-28 16:06
@JiangYongKang all the warnings you see are stating that you won't get cmatrix fonts working on macOS. I have'nt had a hand into macOS, so I don't exactly know the cause, I don't think it works natively and homebrey has an old version of cmatrix. We will be happy to have a port if you could deliver one.

**Comment by abishekvashok** [comment] 2018-02-02 08:32
Closing this as it is provided by `brew`

**Closed as completed by abishekvashok** 2018-02-02 08:32 UTC
