### ISSUE TITLE
Crashes when terminal is less than 2 lines high

### ISSUE THREAD

**Issue by ghost** [abishekvashok/cmatrix#47] opened 2018-06-16 14:20 UTC
I am submitting a bug report.

When  cmatrix is running, and the terminal is resized to less than two lines, cmatrix crashes with the following error:

`996 floating point exception  cmatrix`

To fix it, I suggest cleanly exiting when the terminal is too small, rather than crashing. I can add a quick solution to prevent a harsh exit, however further investigation may be required to find the source of the error.

**Comment by tansly** [comment] 2019-07-14 10:05
I cannot reproduce this. Looks like it was fixed in #8. 

Can this be closed?

**Comment by abishekvashok** [comment] 2019-07-14 12:06
Yep this can be closed

**Closed as completed by abishekvashok** 2019-07-14 12:06 UTC
Labels: Bug
